name: distAI
channels:
  - defaults
dependencies:
  - flask=3.0.3
  - flask-socketio=5.3.6
  - flask_cors=4.0.0
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - numpy=2.0.0
  - pip=24.0
  - python=3.12.4
  - python-socketio=5.11.3
  - pytorch=2.3.1
  - requests=2.32.3
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - torchvision=0.18.1
